Update Session.java
apache/incubator-eventmesh pull request #3046
Opened 2023-02-04 09:25 UTC by himansh295

Overriding hashCode function #issue-998

Fixes #<XXXX>.

### Motivation

*Explain the content here.*
*Explain why you want to make the changes and what problem you're trying to solve.*

### Modifications

*Describe the modifications you've done.*

### Documentation

- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2023-02-07 08:10 UTC, xwm1992 requested changes

2023-02-07 08:10 UTC, xwm1992 commented on eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
> +        result += 31*result + eventMeshTCPConfiguration!=null?Objects.hash(eventMeshTCPConfiguration);
@himansh295 These code can't be compiled please fix.

2023-02-07 12:02 UTC, xwm1992 requested changes

2023-02-07 12:02 UTC, xwm1992 commented on eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
> +        result += 31*result + client!=null?Objects.hash(client) : 0;
result += 31 * result + client!=null?Objects.hash(client) : 0; -> result += 31 * result + (client!=null?Objects.hash(client) : 0);

2023-02-07 12:12 UTC, himansh295 commented on eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java
> +        result += 31*result + client!=null?Objects.hash(client) : 0;
Sure @xwm1992

2023-02-07 12:55 UTC, himansh295 commented
Its throwing error on whitespace indentation after ? on line 288-290 in https://github.com/himansh295/incubator-eventmesh/edit/himansh295/issue-998/eventmesh-runtime/src/main/java/org/apache/eventmesh/runtime/core/protocol/tcp/client/session/Session.java

Why is it happening?

2023-02-07 20:30 UTC, himansh295 commented
@xwm1992 Can you please tell where to write the test cases to cover the above lines

2023-02-08 01:49 UTC, xwm1992 commented
> @xwm1992 Can you please tell me in which class I have to write the test cases for covering the hashCode function?

despite the code test coverage, everything is ok.

2023-02-08 01:51 UTC, xwm1992 approved these changes

2023-02-08 01:55 UTC, merged