eventmesh-admin-rocketmq submodule and createTopic draft API
apache/incubator-eventmesh pull request #530
Opened 2021-09-21 16:14 UTC by yzhao244

Fixes ISSUE #435 #346

### Motivation

The purpose of this PR is for contributing eventmesh-admin-rocketmq module which exposes createTopic REST API to client.

### Modifications

A new eventmesh-admin-rocketmq module is created along with admin controller related files for exposing createTopic REST APIs.

### Documentation

- Does this pull request introduce a new feature? yes
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)
- If a feature is not applicable for documentation, explain why?
- If a feature is not documented yet in this PR, please create a followup issue for adding the documentation

2021-09-26 12:54 UTC, qqeasonchen requested changes

2021-09-26 12:54 UTC, qqeasonchen commented on eventmesh-admin/README.md
> +### POST /clientmanage/topics
@yzhao244 I suggest /topicmanage instead of /clientmanage/topics here, what do you think?

2021-10-03 05:39 UTC, qqeasonchen commented
@yzhao244 admin moudle may need a store like kv or mysql etc to persist the metadata, please consider it, thanks.

2021-10-03 05:44 UTC, qqeasonchen commented
> @yzhao244 admin moudle may need a store like kv or mysql etc to persist the metadata, please consider it, thanks.

@yzhao244 also you can register it to registry, and give a implementation of registry, thanks.

2021-11-27 01:54 UTC, yzhao244 commented
@qqeasonchen conflict fixed. is it urgent to fix the code style check error? :)

2021-11-27 04:16 UTC, qqeasonchen commented
> @qqeasonchen conflict fixed. is it urgent to fix the code style check error? :)
 it is better to fix it.

2021-11-27 06:21 UTC, yzhao244 commented
> > @qqeasonchen conflict fixed. is it urgent to fix the code style check error? :)
> > it is better to fix it.

all fixed :)

2021-11-29 02:14 UTC, xwm1992 approved these changes
LGTM

2021-11-29 02:17 UTC, merged