[ISSUE-883] Transitively export the dependencies of [eventmesh-sdk-java] to other module
apache/incubator-eventmesh pull request #884
Opened 2022-05-21 09:05 UTC by HoffmanZheng

Fixes ISSUE #883 .

### Motivation

[eventmesh-sdj-java](https://mvnrepository.com/artifact/org.apache.eventmesh/eventmesh-sdk-java) is a library module, should transitively export the dependencies, which are necessary for development of [eventmesh-application](https://github.com/apache/incubator-eventmesh/tree/master/eventmesh-examples).

### Modifications

Add gradle plugin [java-library](https://docs.gradle.org/current/userguide/java_library_plugin.html) in eventmesh-sdk-java

Change the configuration of following dependencies from `implementation` to `api`: 
* project(":eventmesh-common")
* io.cloudevents:cloudevents-core
* io.cloudevents:cloudevents-json-jackson
* io.openmessaging:openmessaging-api
* org.projectlombok:lombok:1.18.22

### Documentation

Not a new feature, thus no doc needed.

2022-05-21 09:34 UTC, HoffmanZheng reviewed
Though [maven-publish](https://github.com/apache/incubator-eventmesh/blob/53c62509012dafa4d0912f9f7cb35d5be6c11389/build.gradle#L52) is included in the project, there should be a committor to do the related test.

2022-05-21 09:36 UTC, HoffmanZheng reviewed
Though [maven-publish](https://github.com/apache/incubator-eventmesh/blob/53c62509012dafa4d0912f9f7cb35d5be6c11389/build.gradle#L52) is included in the project, there should be a committor to do the related test.

2022-05-21 09:36 UTC, HoffmanZheng commented on eventmesh-sdk-java/build.gradle
> +    id 'com.github.johnrengelman.shadow' version '7.1.2'
After I use the `java-library` and change the dependency configuration to `api`, the built jar file still does not contain the dependencies.
Thus the `shadow` plugin used here to generate a fat jar. (for your [reference](https://discuss.gradle.org/t/how-to-include-dependencies-in-jar/19571))

2022-05-22 12:31 UTC, ruanwenjun commented
Good catch. Right now, the scope of `eventmesh-common` in `eventmesh-sdk-java` is `implementation`, so if we want to use eventmesh-sdk-java in our app, we need to add the `eventmesh-common` to our dependency. We need to change the scope from `implementation` to api to solve this.

And I think we don't need to make a shawdow jar. cc @xwm1992

2022-05-23 01:35 UTC, HoffmanZheng commented
> Good catch. Right now, the scope of `eventmesh-common` in `eventmesh-sdk-java` is `implementation`, so if we want to use eventmesh-sdk-java in our app, we need to add the `eventmesh-common` to our dependency. We need to change the scope from `implementation` to api to solve this.
> 
> And I think we don't need to make a shawdow jar. cc @xwm1992

Currently I'm trying to use the following script to generate a fat jar of [eventmesh-sdk-java], sometimes it works. Mark the PR work in progress.

```
jar {
    from {
        configurations. runtimeClasspath.filter{ it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

2022-05-23 05:38 UTC, ruanwenjun commented
> > Good catch. Right now, the scope of `eventmesh-common` in `eventmesh-sdk-java` is `implementation`, so if we want to use eventmesh-sdk-java in our app, we need to add the `eventmesh-common` to our dependency. We need to change the scope from `implementation` to api to solve this.
> > And I think we don't need to make a shawdow jar. cc @xwm1992
> 
> Currently I'm trying to use the following script to generate a fat jar of [eventmesh-sdk-java] (without the usage of `shadow` plugin), sometimes it works. Mark the PR work in progress.
> 
> ```
> jar {
>     from {
>         configurations. runtimeClasspath.filter{ it.exists() }.collect { it.isDirectory() ? it : zipTree(it) }
>     }
> }
> ```

I suggest we just change the scope of `eventmesh-commom` to `spi` is enough.

2022-05-25 12:37 UTC, HoffmanZheng commented
I used to use the `gradle jar` and `mvn install:install-file` to do dependencies resolving test, and it does not work.
Rather using `gradle publishToMavenLocal`, the dependencies could be transitively exported to other module!

2022-05-26 02:00 UTC, ruanwenjun requested changes

2022-05-26 02:00 UTC, ruanwenjun commented on eventmesh-sdk-java/build.gradle
> +
It seems this already defined at root `build.gradle`
```suggestion
```

2022-05-26 02:03 UTC, qqeasonchen commented
@HoffmanZheng any update？

2022-05-26 06:03 UTC, HoffmanZheng commented on eventmesh-sdk-java/build.gradle
> +    api 'org.projectlombok:lombok:1.18.22'
also make sense to me, seems the `eventmesh-example` uses that only for log. it's not necessary to export to the users of `eventmesh-sdk-java`
https://github.com/apache/incubator-eventmesh/blob/c055e8324fd6b0c67055b2f4c6731f386acdb5a4/eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java#L42
https://github.com/apache/incubator-eventmesh/blob/c055e8324fd6b0c67055b2f4c6731f386acdb5a4/eventmesh-examples/src/main/java/org/apache/eventmesh/http/demo/sub/controller/SubController.java#L56

2022-05-26 06:03 UTC, HoffmanZheng commented
> @HoffmanZheng any update？

updated

2022-05-26 13:10 UTC, ruanwenjun approved these changes
LGTM

2022-05-27 01:37 UTC, merged